- include: "repos.yml"
  static:  yes
  when:    ansible_os_family == "CentOS"

- include: "sources.yml"
  static:  yes
  when:    ansible_os_family == "Debian"

- include: "tests.yml"
  static:  yes
  when: repos.tests is defined
